apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc1
  namespace: jenkins
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce