apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: default         # اسم الـ ServiceAccount اللي هتستخدمه
  namespace: jenkins   # namespace بتاع الـ ServiceAccount
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
