apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: dev
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/mysql"
